### ISSUE TITLE
Buy a domain name

### ISSUE THREAD

**Issue by stoolwitch** [Donut-Jam-Studios/website#7]
i have by far enough storage and bandwidth on my infomaniak plan, can host it there.

as for the domain name, loic and I agree to keep it simple like donutjamstudios.extention

as for the extension, nothing fancy. my propositions:

.com 

basic, does the job, 15.- per year

.ch 

10.- per year, highlights the fact that we are Swiss: known for the high quality design etc, problem: we are not all Swiss actually

.net

funny internet nerd extension, 15.- per year

**Comment by lacpe** [comment]
How about: both .com & .ch and just have one of them mirror the other?

**Comment by stoolwitch** [comment]
> How about: both .com & .ch and just have one of them mirror the other?

yea sure why not actually, we can afford it methinks

**Comment by lacpe** [comment]
> yea sure why not actually, we can afford it methinks

Do you want to do it when you have time? I'll twint you the total :)

**Comment by stoolwitch** [comment]
the domain name is donutjamstudios.ch
